# Site Settings
title               : Nagajamu.com
owner               : "DeerRIDER"
## url                : "https://nagajamu.com"
## baseurl            : ""
permalink           : /:title/
description         : "Personal notes of DeerRIDER"
markdown            : kramdown

# Where things are
source              : .
destination         : ./_site
collections_dir     : collections
plugins_dir         : src/_plugins # takes an array of strings and loads plugins in that order
layouts_dir         : src/_layouts
data_dir            : src/_data
includes_dir        : src/_includes
sass:
  sass_dir          : src/_sass

# Collections
collections:
  cheatsheet:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : name
  formal_method:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Formal Method"
  mathematics:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : name
  modern_ai:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Modern AI"
  operating_system:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Operating System"
  pl_practice:
    output          : true
    permalink       : /:collection/:title/
    alias           : "PL Practics"
  pl_theory:
    output          : true
    permalink       : /:collection/:title/
    alias           : "PL Theory"
  posts:
    output          : false
    alias           : "Others"
  theorem_proving:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Theorem Proving"
  theoretical_cs:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Theoretical CS"
  type_theory:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Type Theory"
    
# Social Media Accounts
email               : "akiritsu@outlook.com" 
linkedin            : 
github              : "akiritsu" 
gitlab              :
website             :
twitter             :
facebook            :
instagram           :
youtube             :
steam               :
weibo               :

# Global Variables
statement           : "Designed by DeerRIDER, All Rights Reserved"
toc_level           : 3
bgtext              : "ABCFGHKLMNPQRSVWXYZabcdefghijklmnopqrstuvwxyz@#$%&*+-;/[]<>~" # texts randomly displayed in background
# Disqus settings（disqus.com）
disqus_username     : akiritsu

# Default page configuration
defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
  -    
    scope:
      path: ""
      type: notes # file under notes
    values:
      layout: "post"
      tags: n0t3s
      author: aaa
  -    
    scope:
      path: ""
      type: portfolio
    values:
      layout: "post"
      tags: pfl

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
# Cross-Origin Resource Sharing header
webrick:
  headers:
    Access-Control-Allow-Origin: "*"