title: 那伽邪無
owner: DeerRIDER
baseurl: ""
url: "http://nagajamu.com"
permalink: /:title/
notes: "http://nagajamu.com/notes"

personal_link: http://nekiri.com
github_username:  akiritsu
email: akiritsu@outlook.com
weibo_username: 5786851727
zhihu_username: luowangqiankun
disqus_shortname: akiritsu

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "\n\n\n\n"
plugins:
 - jekyll-sitemap
 - jekyll-mermaid


