# Endless loop...

(define (my-foreach proc lst)
  (define (control-stream proc lst)
    (define (control return)
      (call/cc
       (lambda (x)
         (if (null? (cdr lst))
             (void)
             (begin (set! control x)
                    (return '(proc (car lst)))))))
      (return '()))
    (define (generator) (call/cc control))
    generator)
  (define do-loop (control-stream proc lst))
  (set! var do-loop)
  (if (not var)
      (begin (printf var)
             (do-loop))
      (void)))
